//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStatu
    {
        public int ProjectStatusId { get; set; }
        public int ProjectId { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Project Project1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual ProjectStatu ProjectStatus1 { get; set; }
        public virtual ProjectStatu ProjectStatu1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
